TITLE = "A.C.T. - Agent de Corruption Temporel"

WIDTH = 16 # tiles
HEIGHT = 16

TILES_WIDTH = 8 # pixels
TILES_HEIGHT = 8

WIDTH_PIXELS = WIDTH * TILES_WIDTH # pixel
HEIGHT_PIXELS = HEIGHT * TILES_HEIGHT

NB_TURNS = 3
NB_ROUNDS = 3
