TITLE = "A.C.T. - Agent de Corruption Temporel"

WIDTH = 8 # tiles
HEIGHT = 8

TILES_WIDTH = 16 # pixels
TILES_HEIGHT = 16

WIDTH_PIXELS = WIDTH * TILES_WIDTH # pixel
HEIGHT_PIXELS = HEIGHT * TILES_HEIGHT

NB_TURNS = 3
NB_ROUNDS = 3
